#ifndef SPPZCARTOGRAPHY_GLOBAL_H
#define SPPZCARTOGRAPHY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPPZCARTOGRAPHY_LIBRARY)
#  define SPPZCARTOGRAPHYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SPPZCARTOGRAPHYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SPPZCARTOGRAPHY_GLOBAL_H
