#ifndef WINDOWMANAGER_GLOBAL_H
#define WINDOWMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WINDOWMANAGER_LIBRARY)
#  define WINDOWMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WINDOWMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WINDOWMANAGER_GLOBAL_H
