#ifndef SPPZCLASSIFIERTOQT_GLOBAL_H
#define SPPZCLASSIFIERTOQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPPZCLASSIFIERTOQT_LIBRARY)
#  define SPPZCLASSIFIERTOQTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SPPZCLASSIFIERTOQTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SPPZCLASSIFIERTOQT_GLOBAL_H
